### ISSUE TITLE
Not all options update command output

### ISSUE THREAD

**Issue by Kelvin-Lee** [sourcegraph/support-generator#4]
A subset of the deployment-type-and-function selections do not update the command output.

Here are a few examples:

- Docker -> "List Containers"
- Docker Compose -> "Install/Run Sourcegraph"
- Kubernetes -> "Port Forward Sourcegraph"

I did not check all of them. No errors in the developer console.

**Comment by airamare01** [comment]
Yeah confirmed the same when I cloned from the` bee-dev` branch

**Comment by abeatrix** [comment]
@Kelvin-Lee @airamare01 that’s weird. have you installed all the dependencies? I have deployed the app and it works fine as far as I can tell: https://supportgenerator.netlify.app/
